apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    git-commit-hash: f9f5aa2e1e4d8c8868b3d9a69b484b9c75946912
    volume.beta.kubernetes.io/storage-class: slow
  name: pv0003
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp
  persistentVolumeReclaimPolicy: Recycle
