apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    git-commit-hash: cc134cd159447ecf1b10f9793de4a2588ac0fc2c
  name: nginx-a
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        app: nginx
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
