apiVersion: v1
kind: Pod
metadata:
  annotations:
    git-commit-hash: cc134cd159447ecf1b10f9793de4a2588ac0fc2c
  name: test-ebs
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: test-volume
  volumes:
  - awsElasticBlockStore:
      fsType: ext4
      volumeID: vol-02dcd863d6b09b41c
    name: test-volume
