apiVersion: v1
kind: Pod
metadata:
  annotations:
    git-commit-hash: d8b4cd1e8e3ef2db940d1daff9695dad42cc005b
  name: test-ebs
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: test-volume
  volumes:
  - awsElasticBlockStore:
      fsType: ext4
      volumeID: vol-02dcd863d6b09b41c
    name: test-volume
