apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    git-commit-hash: cc134cd159447ecf1b10f9793de4a2588ac0fc2c
    volume.beta.kubernetes.io/storage-class: slow
  name: pv0003
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp
  persistentVolumeReclaimPolicy: Recycle
