
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang/dep"
  source = "https://github.com/kubepack/dep.git"
  branch = "dep-bypass"

[[constraint]]
  revision = "019ae5ada31de202164b118aee88ee2d14075c31"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=v1.8.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/docker/docker"

[[constraint]]
  branch = "=master"
  name = "github.com/docker/distribution"

[[override]]
  branch = "master"
  name = "github.com/docker/distribution"

[[override]]
  branch = "parse-constraints-with-dash-in-pre"
  name = "github.com/Masterminds/semver"
  source = "https://github.com/carolynvs/semver.git"
