# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "1.12.0"

[[constraint]]
  branch = "master"
  name = "github.com/appscode/go"

[[constraint]]
  branch = "release-6.0"
  name = "github.com/appscode/kutil"

[[constraint]]
  branch = "master"
  name = "github.com/evanphx/json-patch"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang/dep"
  source = "https://github.com/kubepack/dep.git"
  branch = "dep-bypass"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/jpillora/go-ogle-analytics"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.9.0"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "e14a70c556c8e0db173358d1a903dca345a8e75e"

[[override]]
  name = "github.com/imdario/mergo"
  revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.9.0"

[[override]]
  name = "k8s.io/client-go"
  version = "v6.0.0"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.9.0"

[[override]]
  name = "k8s.io/metrics"
  version = "kubernetes-1.9.0"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.9.0"

[[override]]
  name = "github.com/docker/docker"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  branch = "parse-constraints-with-dash-in-pre"
  name = "github.com/Masterminds/semver"
  source = "https://github.com/carolynvs/semver.git"

[prune]
  unused-packages = true
  go-tests = true
