apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    git-commit-hash: f9f5aa2e1e4d8c8868b3d9a69b484b9c75946912
  name: nginx-b
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        app: nginx
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
