apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    git-commit-hash: f9f5aa2e1e4d8c8868b3d9a69b484b9c75946912
  labels:
    app: nginx-dm
  name: nginx-dm
  namespace: default
spec:
  template:
    metadata:
      labels:
        name: busy-dm
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
