apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    git-commit-hash: d8b4cd1e8e3ef2db940d1daff9695dad42cc005b
  name: nginx-c
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        app: nginx
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
