apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    git-commit-hash: 659d24c1e7207e087d903f810d34c641b3c4f741
  creationTimestamp: null
  name: nginx
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      annotations:
        app: nginx1
      creationTimestamp: null
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
status: {}
