apiVersion: v1
kind: Pod
metadata:
  annotations:
    git-commit-hash: cc134cd159447ecf1b10f9793de4a2588ac0fc2c
  name: test-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - hostPath:
      path: /tmp
    name: test-volume
