apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    git-commit-hash: cc134cd159447ecf1b10f9793de4a2588ac0fc2c
  labels:
    app: nginx-dm
  name: nginx-dm
  namespace: default
spec:
  template:
    metadata:
      labels:
        name: busy-dm
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
