apiVersion: v1
kind: Service
metadata:
  annotations:
    git-commit-hash: f9f5aa2e1e4d8c8868b3d9a69b484b9c75946912
  labels:
    app: kubed
  name: kubed-operator
  namespace: kube-system
spec:
  ports:
  - name: api
    port: 8080
    targetPort: api
  - name: web
    port: 56790
    targetPort: web
  selector:
    app: kubed
