---
# Source: mongodb-editor/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: mymongo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodbs.kubedb.com
  name: mymongo
  namespace: demo
---
# Source: mongodb-editor/templates/app_application.yaml
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    kubepack.com/package: '{"kind":"ApplicationPackage","apiVersion":"kubepack.com/v1alpha1","chart":{"name":"mongodb-editor-options","url":"https://bundles.byte.builders/ui/","version":"v0.1.0"},"channel":"Regular"}'
  labels:
    app.kubernetes.io/instance: mymongo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodbs.kubedb.com
  name: mymongo
  namespace: demo
spec:
  assemblyPhase: Ready
  componentKinds:
  - group: ""
    kind: Secret
  - group: ""
    kind: Service
  - group: apps
    kind: StatefulSet
  - group: grafana.searchlight.dev
    kind: Dashboard
  - group: kubedb.com
    kind: MongoDB
  - group: monitoring.coreos.com
    kind: ServiceMonitor
  - group: policy
    kind: PodDisruptionBudget
  - group: policy
    kind: PodSecurityPolicy
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: stash.appscode.com
    kind: BackupConfiguration
  - group: stash.appscode.com
    kind: Repository
  descriptor:
    description: MongoDB Editor UI Options
    icons:
    - src: https://cdn.appscode.com/images/products/kubedb/kubedb-community-icon.png
      type: image/png
    links:
    - description: website
      url: https://byte.builders
    maintainers:
    - email: support@appscode.com
      name: appscode
    type: mongodbs.kubedb.com
  selector:
    matchLabels:
      app.kubernetes.io/instance: mymongo
      app.kubernetes.io/name: mongodbs.kubedb.com
---
# Source: mongodb-editor/templates/kubedb_com_mongo_db.yaml
apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  labels:
    app.kubernetes.io/instance: mymongo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodbs.kubedb.com
  name: mymongo
  namespace: demo
spec:
  clusterAuthMode: keyFile
  podTemplate:
    spec:
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
  replicas: 3
  sslMode: disabled
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut
  version: 4.3.2
